// Death Note mascot/object sprites — generated by tools/pixelart.py.
// Each character/object is a small array of lv_img_dsc_t frames (TRUE_COLOR_ALPHA,
// so they overlay cleanly on any panel colour) plus a frame count, consumed by
// ui_mascot.h's lv_animimg-based player. Re-run the generator after editing a
// build_*() sprite function in pixelart.py; these .c files are checked in.
#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_img_dsc_t *const l_frames[];
extern const uint8_t l_frame_count;

extern const lv_img_dsc_t *const light_frames[];
extern const uint8_t light_frame_count;

extern const lv_img_dsc_t *const ryuk_frames[];
extern const uint8_t ryuk_frame_count;

extern const lv_img_dsc_t *const misa_frames[];
extern const uint8_t misa_frame_count;

extern const lv_img_dsc_t *const nfc_card_frames[];
extern const uint8_t nfc_card_frame_count;

extern const lv_img_dsc_t *const ir_beam_frames[];
extern const uint8_t ir_beam_frame_count;

extern const lv_img_dsc_t *const notebook_frames[];
extern const uint8_t notebook_frame_count;

#ifdef __cplusplus
}
#endif
